import type { MindfulnessExerciseTemplate } from '@/types';

export const MINDFULNESS_EXERCISES: MindfulnessExerciseTemplate[] = [
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    description: 'A technique used by Navy SEALs to calm the nervous system under pressure.',
    category: 'breathing',
    durationMin: 4,
    icon: '🌬️',
    steps: [
      'Sit comfortably with your back straight. Exhale all the air from your lungs.',
      'Inhale slowly through your nose for 4 counts, feeling your lungs fill.',
      'Hold your breath gently for 4 counts.',
      'Exhale slowly through your mouth for 4 counts.',
      'Hold for 4 counts before your next breath.',
      'Repeat this cycle 4 more times.',
      'Notice the calm spreading through your body.',
    ],
    bestFor: ['Pre-exam anxiety', 'Panic', 'Focus loss', 'Overwhelm'],
  },
  {
    id: 'grounding-54321',
    title: '5-4-3-2-1 Grounding',
    description: 'Anchor yourself to the present moment using your five senses.',
    category: 'grounding',
    durationMin: 5,
    icon: '🌿',
    steps: [
      'Take a slow, deep breath and softly focus your gaze around you.',
      'Name 5 things you can SEE right now — notice their colours and shapes.',
      'Name 4 things you can TOUCH — feel their texture against your skin.',
      'Name 3 things you can HEAR — even faint or background sounds.',
      'Name 2 things you can SMELL — be creative if needed.',
      'Name 1 thing you can TASTE — even just the air.',
      'Take one final deep breath. You are here. You are safe.',
    ],
    bestFor: ['Anxiety spirals', 'Before exams', 'Dissociation', 'Panic attacks'],
  },
  {
    id: 'body-scan',
    title: 'Body Scan',
    description: 'Release hidden tension stored in your body with progressive relaxation.',
    category: 'body',
    durationMin: 10,
    icon: '🧘',
    steps: [
      'Lie down or sit comfortably. Close your eyes and breathe naturally.',
      'Bring awareness to your feet. Consciously release any tension there.',
      'Move slowly up to your calves and shins — let them soften completely.',
      'Notice your thighs and hips. Release tightness with each exhale.',
      'Scan your stomach. Let it rise and fall without effort.',
      'Relax your chest, shoulders, and upper back — let them drop.',
      'Release your arms, elbows, wrists, and fingers one by one.',
      'Soften your neck, jaw, and the muscles around your eyes.',
      'Let your forehead smooth out. Your entire body is now relaxed.',
      'Rest in this stillness for a few breaths before returning.',
    ],
    bestFor: ['Study fatigue', 'Sleep issues', 'Physical tension', 'Post-study recovery'],
  },
  {
    id: 'breathing-478',
    title: '4-7-8 Breathing',
    description: 'A natural tranquilizer for the nervous system — powerful for sleep and stress.',
    category: 'breathing',
    durationMin: 4,
    icon: '💨',
    steps: [
      'Place the tip of your tongue against the ridge behind your upper front teeth.',
      'Exhale completely through your mouth, making a soft whoosh sound.',
      'Close your mouth and inhale quietly through your nose for 4 counts.',
      'Hold your breath for 7 counts — keep it comfortable, not forced.',
      'Exhale completely through your mouth for 8 counts with the whoosh sound.',
      'This completes one breath. Repeat 3 more times.',
      'Practice twice daily for best results — especially before sleep.',
    ],
    bestFor: ['Sleep issues', 'Acute stress', 'Anger', 'Anxiety'],
  },
  {
    id: 'stop-technique',
    title: 'STOP Technique',
    description: 'A quick mindfulness reset you can do anytime — even between chapters.',
    category: 'cognitive',
    durationMin: 2,
    icon: '⏸️',
    steps: [
      'STOP — Whatever you are doing, just pause for a moment.',
      'TAKE a breath — One slow, deliberate breath in through your nose.',
      'OBSERVE — Notice your thoughts, feelings, and body sensations without judgment.',
      'Ask yourself: "What do I need right now?"',
      'PROCEED — Continue with your work, now with greater awareness.',
      'This entire practice takes under 60 seconds. Use it between study sessions.',
    ],
    bestFor: ['Study breaks', 'Quick reset', 'Overwhelm', 'Decision fatigue'],
  },
  {
    id: 'loving-kindness',
    title: 'Loving-Kindness',
    description: 'Cultivate self-compassion and reduce harsh self-criticism during exam prep.',
    category: 'cognitive',
    durationMin: 6,
    icon: '💛',
    steps: [
      'Sit comfortably and close your eyes. Take three slow, deep breaths.',
      'Think of yourself as you are right now — studying, striving, doing your best.',
      'Silently repeat: "May I be happy. May I be well. May I be free from stress."',
      'Think of a loved one who supports you. Send them the same warm wishes.',
      'Think of a classmate or fellow aspirant. Send them kindness too.',
      'Finally, extend to all students preparing for exams: "May we all find strength."',
      'Open your eyes gently. Notice warmth in your chest.',
    ],
    bestFor: ['Self-criticism', 'Comparison with peers', 'Motivation loss', 'Loneliness'],
  },
];
